### ISSUE TITLE
Investigate how to better use theme in `navigationOptions`

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#102]
We currently don't have a good way to get theme inside of a screen component's `navigationOptions`. How might we better do this?

## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by burkeshartsis** [comment]
maybe this? https://github.com/satya164/react-navigation-addons#navigationsetoptions

**Comment by burkeshartsis** [comment]
further reading - https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title
helpful issue - https://github.com/react-navigation/react-navigation/issues/1639

**Comment by vinnyjth** [comment]
@redreceipt Came up with a solution here: 
https://github.com/ApollosProject/apollos-prototype/commit/8baf7686786ce4eeaf3c8961c26c65328855e61e

#1043
