### ISSUE TITLE
Add Event Content Tile Card

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1030]
### User Story

<img width="587" alt="Screen Shot 2019-08-29 at 11 03 17 AM" src="https://user-images.githubusercontent.com/2659478/63951928-9ead6600-ca4c-11e9-900d-fd2f9115dbfa.png">

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@conrad-vanl same question as #1029

**Comment by redreceipt** [comment]
we'll need this if we want to do #1033

**Comment by vinnyjth** [comment]
It should be pretty easy to render Events inside a ContentCard out of the box with UI-kit, so really this should be a matter of creating a "EventCardConnected" component

**Comment by redreceipt** [comment]
So you're thinking just render the `ContentCard` as an event but not necessarily use an `EventContentItem` to determine it? Maybe check for the presence of an `EventFeature`?

**Comment by vinnyjth** [comment]
I think we're saying the same thing. We should be able to render `Events`, independently of `ContentItems`, and I think we can get away with creating an `EventCardConnected` that is capable of rendering an Event via ID

**Comment by redreceipt** [comment]
Got it. Makes sense now. And we'll wait to put it in the home or discover feeds until we decide the best course of action.
