### ISSUE TITLE
Discover Tabs Images Go In and Out

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1064]
### Details

This doesn't happen and every time, and I've only seen it on Android, but when scrolling up and down on the discover tab, the images go and in and out

![20190918_152505](https://user-images.githubusercontent.com/2659478/65179655-3ccb9500-da29-11e9-9f1c-e2ae9768bb52.gif)

### Expected Behavior

Images should stay loaded

### Actual Behavior

Images don't stay loaded

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
@conrad-vanl @burkeshartsis have you ever noticed this issue on small android phones? it's been around for awhile I'm just now making an issue for it.

**Comment by burkeshartsis** [comment]
So I may have noticed something similar while doing some perf testing on #1044. Try adding a `console.count()` to the discover feed/feeds (it's a feed of feeds) and see if your getting some rerenders. It it seems strange that it would be render related just because you scrolled but it would be the first place I would start.

Another place you could look is to check the docs on the individual feedviews and see if it's doing any kind of "off screen" optimizations by default that we might need to adjust.

**Comment by redreceipt** [comment]
This one is difficult to pin down, I haven't been able to reproduce in a debug environment yet.

**Comment by redreceipt** [comment]
it kinda looks to me like loading states are going in and out

**Comment by conrad-vanl** [comment]
All of our feedviews are flatlists, so yeah, they do render/unrender when scrolling elements off screen. And on top of that, react-native, esp on android, is notoriously slow at displaying "cached" images. It's why things like this exist - https://github.com/DylanVann/react-native-fast-image

If this is why images are doing this, not sure on fix...

**Comment by conrad-vanl** [comment]
FWIW @redreceipt we'd probably strongly consider a PR to core that upgrades our image components in core to using `FastImage` 😉

**Comment by redreceipt** [comment]
I'll certainly give it a shot :)

**Comment by redreceipt** [comment]
what seems odd about this issue is that if `FlatList` renders images on-screen and un-renders them off-screen, it looks like that's happening in reverse.

**Comment by redreceipt** [comment]
> FWIW @redreceipt we'd probably strongly consider a PR to core that upgrades our image components in core to using `FastImage` 😉

Ok so this library is awesome! It looks like the bulk of our `ConnectedImage` implementation is handling caching stuff which `fast-image` does well it looks like. Is there anything else I should worry about about porting from `ConnectedImage`?

**Comment by burkeshartsis** [comment]
I'm not sure how we feel about continuing `minAspectRatio` and `maxAspectRatio` but they are pretty important to our new card components so we will at least need to make sure we are solving for the same problem in the new component.

**Comment by conrad-vanl** [comment]
@redreceipt honestly first go around I would keep `ConnectedImage` and just import `FastImage` instead of `Image` inside of it. Then we can slowly remove functionality from `ConnectedImage` we no longer need
