### ISSUE TITLE
Phone numbers in Rock should be standard type

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1107]
### User Story

As a Rock user, I should be able to delete the phone number that the app made for me.

### Description

We are creating phone numbers for new users in a way that does not expose editing that number in the Rock UI and the app has no way to change it either. We should probably be making it the "Mobile" type so the user can change it later if they want.

![Kapture 2019-10-08 at 10 02 14](https://user-images.githubusercontent.com/2659478/66405505-3a20e780-e9b8-11e9-8daa-c3bf342e1acb.gif)

### Why

Currently, if their number changes, I don't see anyway to delete or change that number without SQL.

### Acceptance Criteria

- [ ] It should add new phone numbers with the "Mobile" type designation

### Other Resources

- Design mockup/prototype link
- Basecamp todo or link to "epic" on GitHub

**Comment by conrad-vanl** [comment]
Word. I didn't know about this. @vinnyjth any ideas? @redreceipt any ideas on how to fix at a code lveel?
