### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1125]
### Details

![Screenshot_20191013-174243](https://user-images.githubusercontent.com/2659478/66722903-10652780-ede1-11e9-93d5-ef9ed796abc9.png)

We should have a plan for landscape mode, currently it looks pretty bad. We could disable (except for videos) until we have a design plan???

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by richarddubay** [comment]
@vinnyjth I started working on this a bit. I have a branch in core (https://github.com/ApollosProject/apollos-prototype/tree/lock-orientation ) that locks the orientation. This works great. But it doesn’t allow the video to be landscape. So it won’t work.

Might need something more like https://github.com/yamill/react-native-orientation , but I know y'all have been hesitant to add new packages.

**Comment by conrad-vanl** [comment]
Locking orientation, as @richarddubay discovered, is actually VERY difficult to do well. Instead, we will be working on better landscape + tablet styles. Closing this issue as we have this tracked in our project management (Basecamp). Thanks!
