### ISSUE TITLE
Swipe-to-Close on Modals is no Longer Reliable

### ISSUE THREAD

**Issue by erikkgagewhitt** [ApollosProject/apollos-apps#1140]
### Details

This particular bug was a tradeof of #1137, and while that needs to be merged to fix a different issue, it is still important to log and fix this issue.

On all modal screens except devotional content items (specifically the tab view), closing the modal by swiping is not useful or reliable.

### Expected Behavior

The modal screens should close easily through swiping.

### Actual Behavior

The modal screens rely on the native modal responders.

### Possible Fix

The reason for the bug is adding pointerEvents={'box-none'} to the view which contains navigation action buttons. Touch events now pass through the view (usually to an image that has a scroll interaction) and therefore does not close the modal as easily as it should.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

Open any content item and experiment with swipe-to-close

### Stack Trace

</details>

**Comment by conrad-vanl** [comment]
This will be fixed in react-navigation-v5 upgrade
