### ISSUE TITLE
Show Dates on Content

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1158]
### User Story

As a user reading content, I may want to know the date certain pieces of content were published (news and stories)

### Description

Conditionally show the date on content items. Series can even have date ranges. Could be on preview cards and a full screen content page. 

Inspiration:

![Screen Shot 2019-10-24 at 4 20 03 PM](https://user-images.githubusercontent.com/2659478/67522165-3e1c5d00-f67a-11e9-8211-d4173e0490d6.png)

![Screen Shot 2019-10-24 at 4 21 22 PM](https://user-images.githubusercontent.com/2659478/67522214-568c7780-f67a-11e9-8da9-75ff97c25bbb.png)

![Screen Shot 2019-10-24 at 4 22 40 PM](https://user-images.githubusercontent.com/2659478/67522305-876cac80-f67a-11e9-88ca-49c362adc65e.png)

### Why

It's useful info

### Acceptance Criteria

* [ ] It should have a content item with the date showing
* [ ] It should have the ability to specify which channels show the date

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@kevin-birdy what do you think about this one?

**Comment by kevin-birdy** [comment]
Funny you bring this up I was just talking about this with @burkeshartsis today.

In Sketch/Figma I actually reserve the top left for date (thinking it would be especially beneficial for sermons, series, etc.) we just haven't implemented it yet.
<img width="516" alt="Screen Shot 2019-10-24 at 6 24 28 PM" src="https://user-images.githubusercontent.com/41083408/67534523-b5a6b800-f68b-11e9-8bd0-799b0b0b9cf1.png">



If it's in this location it can be standardized across all card components without having to worry about vertical real estate within `HorizontalContentCard` which has a fixed height.

**Comment by redreceipt** [comment]
Well you gimme the word and show me the mockups and I'll implement it.

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by conrad-vanl** [comment]
> Well you gimme the word
Word.

> show me the mockups 
We have none besides the cards above :/
