### ISSUE TITLE
Preview Flags on Inactive Content

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1159]
### User Story

As a developer or content team member, I want to know what content is not published yet and what content is live.

### Description

Now that we have the ability to show or not show inactive content, a simple "Preview" flag on the content cards and full-screen content pages would suffice. We just need something to know what content is live and what isn't yet. It doesn't have to be complicated as this will only be used by internal folks.

Inspiration: 

(Swap "Edit" for "Preview")
![Screen Shot 2019-10-24 at 4 20 03 PM](https://user-images.githubusercontent.com/2659478/67522583-fa762300-f67a-11e9-8cf9-746cce5004e0.png)

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@kevin-birdy what do you think about this one?

**Comment by kevin-birdy** [comment]
I like it and agree the last thing we need is to make it more complicated. My only concern is if an icon (`Like` most likely) is present in the top right they would conflict.

**Comment by redreceipt** [comment]
What about the top-middle?

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by kevin-birdy** [comment]
Ya that's what I was thinking 👍

**Comment by redreceipt** [comment]
Excellent! You do the hard part, I’ll do the easy part :)

—
Michael

**Comment by conrad-vanl** [comment]
I don't think we have any appetite on this currently from a core perspective. Closing for that reason, feel free to open a PR.
