### ISSUE TITLE
Video Scrubber Hard to Grab

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1192]
### User Story

As a user, I should be able to scrub the video easily.

### Description

The video scrubber is a little hard to grab, we could easily make this better by increasing the size of the tappable area like we've done other places.

![Screenshot_20191104-163119](https://user-images.githubusercontent.com/2659478/68159979-d3dca580-ff20-11e9-859b-8d5122030820.png)

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by conrad-vanl** [comment]
This will be fixed in the media player rewrite
