### ISSUE TITLE
Play Cover Image Should be Different

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1195]
### User Story

As a user looking at a piece of content with a video, I should see a play icon without a redundant image.

### Description

I know the future is to have thumbnails but even when that comes, if there is no thumbnail provided, we should default the background of the play to be something other than the cover image of the content.

![original (1)](https://user-images.githubusercontent.com/2659478/68220360-a1c95300-ffb5-11e9-9473-db2487b4521b.jpg)

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by conrad-vanl** [comment]
On some apps we've added a `thumbnailImage` to the schema and over-rode the fragment on the client to use `thumbnailImage` for this thumbnail.

I'd like to find a way for this to make it into core, but not sure how we can do that well....

Example of doing this: https://github.com/watermarkchurch/theporch-apollos/blob/master/ThePorch/loadConfig.js#L57
