### ISSUE TITLE
Add Waiting Loader/Spinner for Search Results

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-apps#1198]
### User Story
As someone who uses search, if there is a large number of items for Algolia to search through, it takes a while for visual changes of the search to show on the screen. It would be great if there was a loading indicator to let me know that the app hasn't frozen while searching.

### Description
This is the addition of a loading indicator of some kind to show in between searches.

### Why
This is important because as I switch from one search term to another the app displays the results of the first search term as it waits to load the results from the second search term. It could make the app feel like it's broken if you go from searching for "worship" to "Jesus" but for a few seconds you still see results for "worship".

This seems to be more of an issue with large indexes to search through. I didn't notice this issue as much in the core app as I did when testing the NewSpring app.

### Acceptance Criteria
[ ] It should show a loading indicator in between searches.

**Comment by richarddubay** [comment]
@vinnyjth Also tagging you here for reference.

**Comment by vinnyjth** [comment]
@richarddubay When you search with the newspring app, do you notice any requests to rock being made?

**Comment by richarddubay** [comment]
I didn't look, honestly. I'll do another test and report back.

**Comment by richarddubay** [comment]
@vinnyjth It's actually making a bunch of calls to Rock, but it looks like they are all just pulling content items. They look like this:

`apollos-church-api: While running query: node
apollos-church-api:       Total Network Calls: 6
apollos-church-api:       ContentChannels?%24filter=Id eq 19&%24expand=ChildContentChannels&%24top=1: 1
apollos-church-api: ContentChannelItems/8349?loadAttributes=expanded: 1
apollos-church-api: WistiaMedias?loadAttributes=expanded&%24filter=WistiaHashedId eq 'i4w3ee89h4'&%24select=MediaData: 1
apollos-church-api: ContentChannelItemAssociations?loadAttributes=expanded&%24filter=ChildContentChannelItemId eq 8349: 1
apollos-church-api: Apollos/GetContentChannelItemsByIds?ids=8767&loadAttributes=expanded&%24filter=(((StartDateTime lt datetime'2019-11-06T09%3A45%3A29') or (StartDateTime eq null)) and ((ExpireDateTime gt datetime'2019-11-06T09%3A45%3A29') or (ExpireDateTime eq null))) and (((Status eq 'Approved') or (ContentChannel%2FRequiresApproval eq false)))&%24orderby=Order asc: 1
apollos-church-api: People/GetCurrentPerson: 1
ap`

**Comment by vinnyjth** [comment]
@richarddubay Is that before or after your update to 1.2.1?

**Comment by richarddubay** [comment]
It was after.

**Comment by vinnyjth** [comment]
@richarddubay That's strange - looks like something to do with Wistia. Not sure why, but I can look into it at some point. 

I'm going to keep this open for now, because loading indicators are always good, but I don't believe this is as much of an issue on core because search is lightning fast (because no network requests are made to rock)

**Comment by richarddubay** [comment]
![search](https://user-images.githubusercontent.com/3229463/68315906-88dca280-0086-11ea-94ce-898038772b0c.gif)

**Comment by richarddubay** [comment]
Not sure how it would work differently on core than on ours. But perhaps we don't have the latest search code on ours since the PR I was working off of wasn't entirely up-to-date. Maybe that will change in the next update since we added these pieces now.
