### ISSUE TITLE
Media player crashes if media item has a duration of 0 (can happen with livestreams) 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#1216]
### Apollos Version: x.x.x

![image](https://user-images.githubusercontent.com/1637694/68683940-a5b92000-0535-11ea-8c66-c223190e7179.png)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by conrad-vanl** [comment]
fixed in media player rewrite
