### ISSUE TITLE
Maintain zoom position when switching between campuses

### ISSUE THREAD

**Issue by ridderingand** [ApollosProject/apollos-apps#1235]
### User Story

As a user who is selecting their campus, I want to be able to zoom in to see the geographic location of a given campus, and maintain that zoom position when swiping in between campuses so that I can evaluate their geographic location relative to other campuses.

### Description
This issue is most easily seen through the lens of WC where there are a lot of campuses in a relatively small geographic area. Let's say I zoom in to see just the city of Chicago (and the available WC campuses). Once I swipe to switch to the next campus, it automatically zooms me back out to the USA-level view which eliminates my ability to actually see the location of the selected campus as it relates to the others.

### Why
This change would allow users to easily see where campuses are located in relation to each other _without_ requiring users to constantly zoom back in to inspect the campus grid.

### Possible Implementation & Open Questions
My suggestion is to not zoom back out once a new campus is selected

### Other Resources

![ezgif com-optimize](https://user-images.githubusercontent.com/41083408/69172421-ff33c880-0aba-11ea-95cf-8fa699234ead.gif)

**Comment by vinnyjth** [comment]
@kevin-birdy I think this experience is much better if you are close to the campuses you are scrolling between, it actually feels better for me only because Cincy is closer to Chicago. Might be nice to get Newspring (@richarddubay @redreceipt ) to take a video from their homes and see what their experience is like.

**Comment by cdanwards** [comment]
@kevin-birdy @vinnyjth 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8878532/70636617-db6c2a00-1c03-11ea-99d5-2a0e23b043bf.gif)


The experience isn't jarring if you're within the bounds of the campus or close by.

**Comment by kevin-birdy** [comment]
Works for me then. I'm 100% an edge case.
