### ISSUE TITLE
Wrapping List With Header Crashes Android

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1262]
### Details

This markdown will break content:

`<h1><ol><li>Test</li></ol></h1>`

![Screen Shot 2019-12-08 at 6 09 41 PM](https://user-images.githubusercontent.com/2659478/70398113-227cd400-19e6-11ea-904c-c47ee250b55d.png)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

Open the "Men's Weekend" news article

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
@burkeshartsis @conrad-vanl problem here I think is:

```
<H1>                    -->        <Text>
  <Paragraph>                     <View>
```

I'm trying to look through the `HTMLView` code to think of a solution but the `wrapTextChildren` function is making me cross-eyed, any thoughts on moving forward here?

**Comment by redreceipt** [comment]
I understand `ol` isn't isn't even supported yet, feature I can come back around too later, but switching the content to `<h1><ul>` errors out in the same way

**Comment by conrad-vanl** [comment]
Might not be a problem on newer react-native versions
