### ISSUE TITLE
Swipe Away Home Screen to Onboarding

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1329]
### Apollos Version: x.x.x

User is able to swipe away home screen and get back to onboarding

![dragdownonborading mp4](https://user-images.githubusercontent.com/2659478/73854061-e0aeb500-47ff-11ea-82f3-74c505f265ec.gif)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by redreceipt** [comment]
![Screen Shot 2020-02-05 at 10 12 20 AM](https://user-images.githubusercontent.com/2659478/73854148-03d96480-4800-11ea-9864-a7627b4fe787.png)

**Comment by vinnyjth** [comment]
Fixed in #1339
