### ISSUE TITLE
Checkin Pass Errors

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-apps#1385]
### Apollos Version: x.x.x
1.3.0

### Details
When I tap on the "Checkin" button on the Connect page I get the following:
![Screenshot 2020-03-12 14 19 13](https://user-images.githubusercontent.com/3229463/76555336-cfe00780-646d-11ea-83e8-c75853886e24.png)

### Expected Behavior
I should be able to see my checkin pass.

### Actual Behavior
I just get an error screen instead.

### Steps to Reproduce
1.  Go to the Connect screen
2. Tap on the "Checkin" button
3. Cry a little on the inside (or the outside - that's fine too) when you get an error screen.

**Comment by camrun91** [comment]
I am actually getting this issue now as well.

**Comment by conrad-vanl** [comment]
To troubleshoot this we need someone to find the true error message being thrown. One way to see this is to enable network inspect on the [react-native debugger](https://github.com/jhen0409/react-native-debugger) and look at the response. That response and error message would help us identify this error much quicker.

**Comment by camrun91** [comment]
@conrad-vanl @richarddubay This issue was fixed in our app by making sure the ROOT_URL secret was defined.
