### ISSUE TITLE
Theme Resolver

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1448]
### Details
The current resolver for Theme and Color types and scalars resolve to random colors

### Expected Behavior
When I add a theme field to a schema, I expect the theme to not resolve with random colors.

### Actual Behavior
The current resolver for Theme and Color types and scalars resolve to random colors

### Possible Fix
Build out the default theme resolver in Core so it doesn't require churches to maintain that code in our individual api's

**Comment by conrad-vanl** [comment]
Not a bug, but expected for the church to integrate on their end.
