### ISSUE TITLE
SafeAreaView on UI Media Player

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1449]
### Details
When viewing a view in landscape mode, the seeker gets cut off by the notch

### Expected Behavior
The notch should not cut off any UI elements

### Actual Behavior
See screenshot

### Possible Fix

SafeAreaView

<details><summary>Additional Info</summary>

### Your Environment
iPhone 11 Pro

![IMG_2098](https://user-images.githubusercontent.com/45076058/81001414-ae6c1e00-8e15-11ea-9760-4bf60e9abbb9.PNG)

**Comment by conrad-vanl** [comment]
Fixed in upcoming media player rewrite
