### ISSUE TITLE
iOS Status Bar text gets washed out on anything that isn't the home feed

### ISSUE THREAD

**Issue by richarddubay** [ApollosProject/apollos-apps#151]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Make sure the `<StatusBar />` looks right on every screen

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by cdanwards** [comment]
@burkeshartsis @conrad-vanl After talking with @richarddubay and looking through the app, it seems that this issue has been resolved with some of the latest updates. Do y'all agree?

**Comment by conrad-vanl** [comment]
This is still an issue with the media player, I believe. We should probably make the status bar hiddne when the media player is opened.

You can replicate by starting a video, minimizing the player, closing the content item view, then re-expanding the player

**Comment by richarddubay** [comment]
@conrad-vanl Does the merged PR referenced here fix this issue? If so, this can be closed.

**Comment by richarddubay** [comment]
Just a monthly check in. I'm still guessing this can be closed.
