### ISSUE TITLE
Centralized Routing - Deep Linking, Universal Linking, and Push Notifications

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1522]
### User Story

As a `church/client developer`, I want a `standardize url routing` so that I can `have an easier way to manage custom routing for my org/app`.

### Description
This spec is a new suggested approach for how to handle routing URL's.

### Why
Right now, there are multiple different ways that URL routing is handled inside of the app. This spec proposes that all url routing get passed through a hook that handles the interaction. So any time we want to "listen" for a url (button click, Push Notification, Universal Linking, etc), we route it through a single source that is configurable for each church to manage.

### Acceptance Criteria/Possible Implementation & Open Questions
We've been testing out a concept in the CF app for a little while now that uses a custom hook that take a url and checks to see if it's a deep link. If it is, the user is automatically routed to that location. If it's not, though, it will send that url to the Apollos API where the API will transform the URL into something that the app can route.

Possible Configurations:
1. appname://link/MyRoute ==> immediately deep link you that location in the app
2. https://website.com/deep-link-this ==> return to the client a deep link (appname://link/deep-link-this)
3. https://website.com/in-app-browser ==> return to the client this url back to the client to open up an in-app browser
4. https://website.com/in-app-browser ==> return to the client this url with a descriptor that tells the app to open in an external browser (https://website.com/in-app-browser?mobileAppBrowser=external)

### Other Resources
[CF Link Router Hook](https://github.com/christfellowshipchurch/apollos-app/blob/master/src/hooks/useLinkRouter.js)

**Comment by redreceipt** [comment]
we've made a lot of improvements here, closing in favor of smaller more specific issues.
