### ISSUE TITLE
Survey App for missing Deep Links

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1527]
## User Story

As a developer, I want all screens in the app to be accessible by deep linking so that I can offer my users direct access to **all** content through methods like universal linking and push notifications.

### Description
As we have added so many new experiences in the app, there are some that are currently not accessible through deep linking. As churches are trying to get their congregation to interact with the app more holistically, it will benefit churches to be able to target communication to specific areas of the app. Need more demographic information? Link to the Edit Profile page. Launching prayer and want people to add their requests? Launch to Prayer Experience.

### Why
This is probably available for nearly 90% of the experiences inside of the app as of today. The one that sparked this, for me, was that there is currently no way (that I can see) to link to the Prayer Experience from within the app. This sparked a question for me as to whether or not there are other items like this on the platform.

### Acceptance Criteria
* [ ] A curated list is put together and published of every unique landing screen on the platform (ex. `ContentSingle` for viewing a Content Item, `Discover` for a tab to browsing content, `EditProfile` for editing the current user's profile information, etc.)
* [ ]All unique landing screens and experiences on the app have a way to navigate to them from deep links

#1522 #1508

**Comment by redreceipt** [comment]
Any nav component can be opened via the deep link. closing.
