### ISSUE TITLE
getHomeFeedFeatures --> mapFeedFeatures

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1544]
### User Story

As a `developer` I want to `use feed features in more places in the app` so that I can `developer faster and easier`.

### Description
Make the `getHomeFeedFeatures` method in the Features data-source more generic so that the Feed Features Mapping can be used for more than just the home feed

### Why
At CF, we've seen incredible success with the development process of adding/adjusting Feed Features and we would like to have Feed Features drive our Events, Give, and Profile tab. In order to avoid copy/pasting the `getHomeFeedFeatures` method every time we want to introduce a new Feed of Features

### Acceptance Criteria
```
async mapFeedFeatures(features = []) {
    return Promise.all(
      features.map((featureConfig) => {
        switch (featureConfig.type) {
          case 'VerticalCardList':
            return this.createVerticalCardListFeature(featureConfig);
          case 'HorizontalCardList':
            return this.createHorizontalCardListFeature(featureConfig);
          case 'HeroListFeature':
            console.warn(
              'Deprecated: Please use the name "HeroList" instead. You used "HeroListFeature"'
            );
            return this.createHeroListFeature(featureConfig);
          case 'HeroList':
            return this.createHeroListFeature(featureConfig);
          case 'PrayerList':
            return this.createPrayerListFeature(featureConfig);
          case 'ActionList':
          default:
            // Action list was the default in 1.3.0 and prior.
            return this.createActionListFeature(featureConfig);
        }
      })
    );
  }

getHomeFeedFeatures = () => return this.mapFeedFeatures(get(ApollosConfig, 'HOME_FEATURES', []))
```

* [ ] It should rename `getHomeFeedFeatures` to `mapFeedFeatures`
* [ ] It should add `getHomeFeedFeatures` method that called `getFeedFeatures`

**Comment by redreceipt** [comment]
We've discussed this before but aren't ready to move forward on any implementations. New apps have a separate query for each tab. Can be recreated as a Github Discussion for further conversations.
