### ISSUE TITLE
Order of Children and Parent Content Items is Incorrect

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1627]
### Apollos Version: x.x.x

Rock had a bug in it where the order of the `Content Channel Items Association` was not being populated when saving Children to a Content Channel Item.

This has been remedied as of Rock 10.3, and so now we should update the cursors for Parent and Child to respect the Content Channel Item Association `Order` to make sure that when a Content Manager set the order of Children in Rock, it's reflected properly

### Possible Fix

We resolved this issue in the [CF Apollos API](https://github.com/christfellowshipchurch/apollos-api/blob/master/src/data/content-item/data-source.js#L286). @vinnyjth or @redreceipt if you're good with this, I can open up a PR with this code in Core.

**Comment by redreceipt** [comment]
I’d certainly welcome a PR to look over!
