### ISSUE TITLE
[Content] Related/similar content

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#168]
## User Story

A user can view content related to the content they're looking at.

For example, if a user is reading a story, they can see similar stories beneath it.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by IsaacHardy** [comment]
@conrad-vanl After thinking and discussing this with Rich, it seems that related/similar content will have to have some sort of "tagging" system similar to what we used from EE in Newspring/Apollos. 

However, an potential issue might be trying to get the four main churches to keep their data to a specific tagging format. I'm going to do some research on Rock tagging in general to see if there are solutions for a cohesive tagging format, but wanted to communicate my initial thoughts on this potential issue.

**Comment by conrad-vanl** [comment]
@vinnyjth might be able to weigh in here with ideas too. There's a lot of ways to consider how to find "similar" or said another way, "content you might be interested in". One way might be to leverage data we have from the community - ie... if a lot of users engage with a piece of content that also engage with another piece of content, there's a good chance you'd also engage with the other piece of content. 

I know search isn't on the table, but depending on how we implement search our search infrastructure might also be able to handle this. For instance, Elasticsearch has "More Like This" functionality built in: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

**Comment by conrad-vanl** [comment]
While I think we can think through this some, there's likely no "mvp" implementation for this feature.

**Comment by conrad-vanl** [comment]
I think we should leave it off scope for now.
