### ISSUE TITLE
Switch server to use non-default version of graphql-upload

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1889]

**Comment by redreceipt** [comment]
https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289

**Comment by redreceipt** [comment]
@vinnyjth any other details here?

**Comment by vinnyjth** [comment]
Essentially we can't use Node 12+ until we stop using the built in `apollo-upload` module. We need to turn off apollo's built in upload piece, and then use the external `graphql-upload` package. Instructions are linked in that comment above. 

A good way to test to make sure it's working will be ...

- check the schema docs in the playground and make sure the upload scalar is still there
- the api still boots ;) 
- you should still be able to upload images

After this we can bump the app to the latest node lts.

**Comment by conrad-vanl** [comment]
Is this still an issue?
