### ISSUE TITLE
dark and light mode doesn't switch unless hard closed

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1894]
comes from the `themeprovider`, may need to detect app state changes to propagate new context

**Comment by camrun91** [comment]
@redreceipt I do not think this is fixed in core However our app and one other one this is fixed. I think @conrad-vanl pushed the fix just need to add it to templates.

**Comment by redreceipt** [comment]
this is fixed

![Kapture 2021-07-21 at 20 53 02](https://user-images.githubusercontent.com/2659478/126577186-778d7ae0-e9b7-4a80-bcca-7e4bd4636510.gif)
