### ISSUE TITLE
replace graphql-tag with @apollo/client > gql

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1901]
we could swap out all instances of `graphql-tag` with `import { gql } from '@apollo/client';`

**Comment by nlewis84** [comment]
is this as simple as doing a find/replace across the whole repo on `import gql from 'graphql-tag';` with `import { gql } from '@apollo/client';`?

**Comment by redreceipt** [comment]
Maybe :) try it and then see if the app boots

**Comment by nlewis84** [comment]
App booted, guess so! 👍
