### ISSUE TITLE
landscape mode problems

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1907]
in landscape when viewing an item, the video is extremely cropped, and hitboxes for media controls are very small and centered slightly below the center of the icons

![preview-full-photo_2021-02-05_09-52-56](https://user-images.githubusercontent.com/2659478/116429427-e1bc6f80-a813-11eb-9a6a-7c33b4d38e0a.jpg)

**Comment by conrad-vanl** [comment]
Closing in favor of #2112 (that screenshot is closer to what current app behavior is doing)
