### ISSUE TITLE
IOS Provisional Notifications

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2002]
as of IOS 12 Onesignal added a checkbox on the ios configuration to all the user to set up provisional Notifications. if this is enabled it makes it so the onboarding process does not work as intended. The "Yes get notified" button kicks you out to settings every time.

**Comment by camrun91** [comment]
The code here https://github.com/ApollosProject/apollos-apps/blob/0de8ca3e013e81d097264f8809abca596ec3ebe1/packages/apollos-ui-notifications/src/permissionUtils.js#L48  

always returns granted with values of false for most of the settings.

**Comment by redreceipt** [comment]
> as of IOS 12 Onesignal added a checkbox on the ios configuration to all the user to set up provisional Notifications

can you show me where this is? I don't fully understand the problem

**Comment by camrun91** [comment]
<img width="1792" alt="Screen Shot 2021-06-18 at 10 27 09 AM" src="https://user-images.githubusercontent.com/16566029/122597513-1210d500-d031-11eb-8ae5-49c880fa2aa2.png">
That is a screenshot of the settings on one signal. If that box is checked when someone set up one signal then here is what happens. 

when a user installs that app notification permission is granted, however, it is never asked for, The incoming notifications will come through silently to notification center, They will have an option to keep or turn off. If you select to keep you get another prompt for how you want to receive them.  I will add a screenshot of the notification as it came through for me yesterday.

**Comment by camrun91** [comment]
![image](https://user-images.githubusercontent.com/16566029/122597879-a2e7b080-d031-11eb-8d4a-715867210288.png)

@redreceipt here is how they come through.
