### ISSUE TITLE
can't leave screen after praying for your own prayer

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#2008]
when you come to a prayer that has already been prayed for, you can't get to the next one and you can't close the dialog.

![IMG_74610294789B-1](https://user-images.githubusercontent.com/2659478/122987148-460c3300-d36e-11eb-8bc7-d75bb0684b07.jpeg)

**Comment by conrad-vanl** [comment]
there is a close button?

**Comment by conrad-vanl** [comment]
One solve might be to not have a disabled/"Prayed!" state like we have now, and instead keep the button pressable and add a "You prayed last" timestamp above:

<img width="398" alt="Screen Shot 2021-09-28 at 10 50 16 PM" src="https://user-images.githubusercontent.com/103927/135200267-3d8549c3-cf36-4d1b-a3da-b5a479b002d1.png">

**Comment by redreceipt** [comment]
Ping

**Comment by camrun91** [comment]
What I am about to say will likely need to be in another feature request but plays into this a little. it would be nice if on your own prayers you had the option to mark them as "answered" with a note of how they were answered. I think Rock has this ability although we are not currently using it.
