### ISSUE TITLE
Android: too much space in the header bar

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#2011]
![image](https://user-images.githubusercontent.com/2659478/123267231-c5af1480-d4ca-11eb-8f39-cf708093c8c5.png)

**Comment by camrun91** [comment]
@MatthewKyle22 this is the issue you were looking into.

**Comment by MatthewKyle22** [comment]
@camrun91 yes, I've only found it to be an issue on android devices. Some android models more padding than others.
