### ISSUE TITLE
videos continue to play as you navigate deeper into the stack

### ISSUE THREAD

**Issue by nlewis84** [ApollosProject/apollos-apps#2069]
Start a video, click on one of the video children below (without stopping the video), previous video continues to play in background and new video can be played simultaneously.

https://user-images.githubusercontent.com/72768221/126218537-6385deae-684c-4252-849c-58015a512dbd.mp4

**Comment by camrun91** [comment]
This is the same issue here. https://github.com/ApollosProject/apollos-templates/issues/394 so that one can probably be closed.
