### ISSUE TITLE
Find people to follow full list not visable.

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2077]
From core the find people to follow list on the connect tab you are unable to see all people listed as the view extends beyond the screen. This is present on New springs live app as well as our app in testflight.  This issue should exist on any app that is not customizing that component.

**Comment by MatthewKyle22** [comment]
On the search screen, it looks like changing the height of SearchContainer to 93% gives me a scroll view I'd expect. But I think something else needs to be done besides hardcoding it to 93%?

**Comment by camrun91** [comment]
@redreceipt Just wanted to make sure you saw this one. It happens in a couple of places on the app. I think it is on the follow people and the search results maybe.

**Comment by nlewis84** [comment]
We see it in follow people and search results. Have you all noticed it anywhere else? It's on our radar.

**Comment by redreceipt** [comment]
@nlewis84 don't you have an open PR to fix this?

**Comment by nlewis84** [comment]
Not yet. I have the search results one figured out, but not the follow people one.

**Comment by redreceipt** [comment]
oh, gotcha. thanks for bringing up @camrun91 looks like we're close to a fix

**Comment by camrun91** [comment]
Awesome those two places are the only ones that we have seen them.
