### ISSUE TITLE
Bug: Prayer notifications crash app.

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2091]
I got a notification yesterday from our app (Using core prayer stuff) that someone had prayed for me. Clicking this crashed the app. I tried to see what URL it was trying to open when you click on the notification however I can not find where a URL or data is added to the notification. This is the only line that I can find creating a notification for prayer.

https://github.com/ApollosProject/apollos-apps/blob/792a2b78832aa8c6cb5fb9f90eab733c76bbaad1/packages/apollos-data-connector-rock/src/prayer-request/data-source.js#L122

**Comment by nlewis84** [comment]
Noticed last week that several apps were crashing when you click on notifications. May be related to this.

**Comment by conrad-vanl** [comment]
I believe this has been fixed - at least it's no longer happening on core apps. Can you confirm?
