### ISSUE TITLE
Prayer Feature - Prayers get reordered after "PRAY"

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#2095]
**Apollos Version: 2.4.0**

We noticed an issue recently that we don't quite understand on the Christ Fellowship App's Prayer Experience screens.

If you open up the Prayer Experience and press "pray", the user is moved over to the next Prayer Screen and then after about a second or 2, the prayer re-renders as the prayer they just prayed for:

1. Open Prayer Experience
2. Pray for "Prayer 1"
3. Screen is automatically swiped over to "Prayer 2"
4. Wait 1-3 seconds
5. Screen is automatically swiped back to "Prayer 1"

What I've been able to do in my debugging is confirm that there isn't an extra network request happening, but instead when a single prayer request is found in the cache and updated, the entire cache is re-ordered for the Prayer Request Feature.

What I can't understand is why...? Any thoughts?

**Comment by asleepingpanda** [comment]
Another test ran this morning is proving this to _only_ be happening on iOS devices

**Comment by conrad-vanl** [comment]
@asleepingpanda are you still experiencing this issue? Did you learn anything else about it?
