### ISSUE TITLE
feature: support multiple videos

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2168]
Unless I am just missing it there does not seem to be support for more than one live stream URL. We currently are doing 3 live streams each week. I have built out the UI in the app to support this but am having trouble getting the API to pull more than one live stream URL.

**Comment by conrad-vanl** [comment]
To be clear, you aren't doing more then 1 livestream at a time, just that the URL changes throughout the week?

**Comment by camrun91** [comment]
Nope we are actually doing 3 livestreams at once. I have this working in
our repo. I have not built any tests or anything.

**Comment by conrad-vanl** [comment]
@camrun91 how are you solving this in your repo? We've had plans to add support for multiple videos/audio streams, which could in theory be used to support multiple videos. Something like this [prototype](https://www.figma.com/proto/Nr6TBbkRdYoeHxfAFbd82V/F-and-I-Prototypes?page-id=16%3A4511&node-id=17%3A4512&viewport=303%2C48%2C1.47&scaling=min-zoom&starting-point-node-id=17%3A4512) - would that solve this?

**Comment by camrun91** [comment]
@conrad-vanl I am doing it specifically for live streams. So here is the scenario on a Sunday morning we have 3 services that stream at the same time. They stream 3 times each Sunday. 

I modified the API config to include an array of the live streams so we are leveraging the chop schedule and all that to tell if they are active or not.  that can be seen here https://github.com/CrossingsCommunityChurch/Apollos_apps/blob/2f52f661ccefa0752ff4ab83f97b975e95ff6fb2/apollos-church-api/config.postgres.yml#L35

As far as the feature and the rendering in the app I actually took what @asleepingpanda had implemented and modified it a little those can be seen here. 

https://github.com/CrossingsCommunityChurch/Apollos_apps/blob/master/apollos-church-api/src/data/livestream/data-source.js

and the app UI is here.
https://github.com/CrossingsCommunityChurch/Apollos_apps/tree/master/apolloschurchapp/src/live-feed

There is some clean-up there that needs to be done (Also I need to start building tests it's just something I never learned.) 

I think there is a use case for the prototype you shared. I could see it being used for audio-only vs video. It could be used in this same scenario though just present all options under a dropdown. ours shows up like prayer requests.

**Comment by conrad-vanl** [comment]
@camrun91 yeah, I see this as a both-and for sure. I like what you're doing as far as making live-streams more visible! I think that's great to bring into core. But also supporting multiple videos on a single piece of content in general is what that linked prototype is trying to portray

**Comment by camrun91** [comment]
@conrad-vanl on that note one thing I did notice is it would be nice if there was an easier way to override or add additional features. right now I have to copy the core file and anytime you all update it I have to make sure to catch that you have updated the get features function.

On the live stream thing I can not take all the credit @asleepingpanda did a lot of the heavy UI work. I just recently tied it to the church online stuff you all are doing in core.

**Comment by conrad-vanl** [comment]
> easier way to override or add additional features

This sounds like a good topic for a new issue / discussion 😉
