### ISSUE TITLE
Following screen

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#2205]
Add a followers screen with ability to "Unfollow" someone

[Prototype](https://www.figma.com/proto/Nr6TBbkRdYoeHxfAFbd82V/F-and-I-Prototypes?page-id=8%3A1838&node-id=8%3A1987&viewport=303%2C48%2C0.83&scaling=min-zoom&starting-point-node-id=8%3A1987)

**Comment by tomthornton** [comment]
@conrad-vanl is this a screen for people who follow you or people you are following? I figured it means people who follow you but the "Unfollow" part confused me. Should that button just control whether you are following them back or not?

**Comment by conrad-vanl** [comment]
At minimum, I think this is a screen showing people that you follow, not people that follow you. That way you can unfollow people. 

Past MVP I think we'll need to show both people you follow and people following you. Also, I think @vinnyjth started working on this somewhere and might be able to link to a branch or something.

**Comment by conrad-vanl** [comment]
"Following"
"Followers"

So this is a "Following" screen, I'll change the title 😅

**Comment by tomthornton** [comment]
Okay sounds good. I think I actually did create a PR for this way back when I first started before we got into the shovel

**Comment by conrad-vanl** [comment]
Yeah, maybe you're the one that started on that actually! that sounds familiar.
