### ISSUE TITLE
Bring Phosphor Icons into core

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#2206]
...and replace the current icon set we have

[Phosphor Icons](https://phosphoricons.com) is the open-source icon set we've been using in UI Kit and app prototypes in Figma for nearly a year now. I think we've validated this set to become the core icon set for Apollos. 

They have a couple of different open source options, not sure what is the best solution to bring into core.

**Comment by tomthornton** [comment]
@conrad-vanl found this package that was created recently [https://github.com/duongdev/phosphor-react-native](url) so I believe that will work. Do you have a link to a figma file that has which Phosphor icons to add? For example the read tab icon is just four squares but I'm guessing we'd use a book icon?

**Comment by conrad-vanl** [comment]
Ideally we can use this to replace our current Icon component in a backwards compatible way

**Comment by conrad-vanl** [comment]
And as far as which icons .... could we bring it the entire set?

**Comment by tomthornton** [comment]
@conrad-vanl yep we can. The way icons are used now though is they are hard coded in ui-kit/theme/icons
