### ISSUE TITLE
Expose people connections on content

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#2208]
Some common requests:

- Show speakers on sermons
- Show authors on content
- More granular push notifications based on your interests

With our Postgres database, we're starting to create connections between people, tags, content, etc. Lets figure out how to expose some of these connections and allow people to follow people connected to content:

<img width="452" alt="Screen Shot 2021-09-28 at 10 42 18 PM" src="https://user-images.githubusercontent.com/103927/135199496-ffdfabba-820b-4f30-a92c-882f03484cec.png">

[Prototype](https://www.figma.com/proto/Nr6TBbkRdYoeHxfAFbd82V/F-and-I-Prototypes?page-id=12%3A4179&node-id=13%3A4189&viewport=303%2C48%2C1.05&scaling=scale-down&starting-point-node-id=13%3A4189)

**Comment by camrun91** [comment]
Yes! I actually have this as a to look into for our app.
