### ISSUE TITLE
De-risk audio bible support

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#2221]
Add ability to play the audio for a given scripture feature.

Let's meet to discuss this before starting on it.

**Comment by tomthornton** [comment]
@conrad-vanl as I see it, I think we have three options
- Process and trim the audio clips via the shovel, upload them to S3, and attach these to the scripture features. The downside here is that it may violate api.bible's terms of service.
- Process and trim the audio on the server, which may be a bit more tricky and may result in longer loading times for the full scripture feature.
- Process and trim the audio on the client, which would give us access to the Web Audio API's but is anti-pattern to what we do now. https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by tomthornton** [comment]
This might also be an option
https://www.digitalbibleplatform.com/docs/api-version-2/library-audio/

**Comment by conrad-vanl** [comment]
This is currently blocked waiting on better access from api.bible
