### ISSUE TITLE
Prayer postgres model missing field

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2329]
We currently allow congregates to submit a confidential prayer via rock. We are using the is public field of prayers for this. The Postgres database model is currently missing this. This is causing confidential prayers to show up in the app.

**Comment by camrun91** [comment]
@conrad-vanl @redreceipt I am working on a PR for this. I will also look at the caching of the prayers as there seems to be an issue with that.

**Comment by camrun91** [comment]
I will also look at a PR for the Shovel as well.

**Comment by camrun91** [comment]
#2334

**Comment by redreceipt** [comment]
Oh, I misread the PR. you just don't want them to show up. we can fix that in the shovel, I'm working in there right now. I'll link you once it's done.

**Comment by camrun91** [comment]
@redreceipt I think for our initial release them not showing up is fine. It could be worth the conversation though, It may be neat in the future to allow our prayer team and or staff to see those in app. 

I also have two issues open in the shovel repo. I think I have them both fixed in our repo. If you want PR's for those let me know.
