### ISSUE TITLE
SimpleDonation webview css

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2359]
when you step through a give session with simple donation the last screen I think there is a close button that is not removed currently.

**Comment by camrun91** [comment]
@vinnyjth @redreceipt just updating this I looked into the css on this button and there is not a unique identifier on it. I reached out to taylor at simpledonation to see if they can maybe change the version of merlin to go back to the start on successful donation.

**Comment by redreceipt** [comment]
Can you post a video or screenshot showing what this is?

**Comment by camrun91** [comment]
This is the last screen on the simple Donation widget(not something we can control) that close button closes the widget and leaves an empty tab in the webview. with no way to get back to the widget. 
<img width="465" alt="Screen Shot 2022-02-25 at 8 53 48 AM" src="https://user-images.githubusercontent.com/16566029/155802267-09805600-1ea4-4913-b72b-874cdc4f7452.png">

**Comment by camrun91** [comment]
this is another one that makes the user experience from here not that great.
