### ISSUE TITLE
Support getting notified on more than one device. 

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2370]
I think this is partially supported right now. 

Currently there are two ways we are sending onesignal who should be getting notified 
1. include_external_user_ids this looks to possibly be notifying all devices a user has. 
2. the other way is using include_player_ids when this is used it looks for one specific device ID. 

the issue is with case 2 when I have a new device I log into the other ones are not getting notifications when someone prays for my prayer.

**Comment by camrun91** [comment]
@redreceipt @vinnyjth this one goes along with the postgres prayer stuff from last week. I can chat some time if I need to about what I am seeing.

**Comment by camrun91** [comment]
@redreceipt I can possibly make a PR for this based on the changes I made to get it working at crossings. However, I am not sure what if anything the changes would impact. It looks like these notifications are getting triggered in a few different ways some using the notifications in the Postgres data source and some not.

**Comment by redreceipt** [comment]
Go for it

**Comment by vinnyjth** [comment]
We should/need to migrate all notifications to be fired through the Postgres datasource, so including that in any work in this area would be great :)

**Comment by camrun91** [comment]
Cool I will take a look at getting this PR up this afternoon.

**Comment by camrun91** [comment]
for you all to look at here is a patch file of the changes I made to get this working. https://github.com/CrossingsCommunityChurch/crossings-apollos-api/blob/81ee4db99b469a7f9933a3905ff27fc8cb3e98b0/patches/%40apollosproject%2Bdata-connector-postgres%2B2.42.0.patch#L18


I will fully admit that I do not 100% understand the full flow of the notifications but I am getting closer to understanding them.
