### ISSUE TITLE
Webview won't allow Apple Pay

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-apps#2417]
Crossings is using Simple Donation via the webview feature. However we are running into an issue where the webview is not allowing apple pay to show in the merlin widget. @taylorbooks from simple and myself narrowed it down to possibly being a known issue in the version of "React-native-webview" that core is using.

I did try to update the package in Crossings repo locally and it still failed in the sim. 

I would be more than happy to work with someone to get this working as it is a big ask by our finance team to have this available at launch

**Comment by camrun91** [comment]
@conrad-vanl I do not know who should be tagged in this.

**Comment by camrun91** [comment]
@conrad-vanl @redreceipt @vinnyjth this one would be nice for those of us using simple donation. I narrowed it down to something to do with the react-native webview. If it is in the plan to do a more "full integration" we can let this close but for now, I would like to see if we can get merlin to be fully functional in-app.

**Comment by redreceipt** [comment]
Go for it
