### ISSUE TITLE
[Toolkit] Add Developer / Tester "Toolkit"

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#324]
## User Story

As a developer  I want to have access to a an in-app control panel so that I can test the livestream.
As an app tester  I want to have access to a an in-app control panel so that I can test push notifications.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by IsaacHardy** [comment]
@vinnyjth Is this needing to be closed?

**Comment by vinnyjth** [comment]
@IsaacHardy Not yet, as I haven't accomplished all the objectives within :)
