### ISSUE TITLE
Login screen SafeAreaView and padding issues

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-apps#368]
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by redreceipt** [comment]
@conrad-vanl I figured this one out while working on #369, why are we using a custom `BottomSafeAreaView`? `SafeAreaView` looks great.

![screen shot 2018-11-19 at 4 13 08 pm](https://user-images.githubusercontent.com/2659478/48735303-05783600-ec16-11e8-8bc4-0a3e87c6b690.png)

**Comment by vinnyjth** [comment]
@burkeshartsis Can you define the padding issues here?

**Comment by burkeshartsis** [comment]
@vinnyjth

<img src="https://user-images.githubusercontent.com/2053547/58908947-dc198600-86df-11e9-8150-2fd8152adca0.png" width="50%" />

**Comment by redreceipt** [comment]
I can take swing at this

--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599
