### ISSUE TITLE
[EPIC] Implement Rock Plugin for Push Notifications

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#469]
## User Story

As a `church user` I want to `send push notifications from within Rock` so that I can `utilize the data that Rock knows about my people to segment and customize push notifications`.

#### Problem Details _(Optional)_

* Hopefully this is some sort of plugin that we can easily distribute to other Rock churches - can we add it to the Rock plugin store?
* Set up as a communication transport?

**Comment by richarddubay** [comment]
@conrad-vanl @vinnyjth How do y'all feel about closing this? The OneSignal plugin is done, right?

**Comment by richarddubay** [comment]
Just a monthly check in. I feel like this can probably be closed.
