### ISSUE TITLE
HMW: plug and play splash screen and icons for partner churches

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#559]
- [ ] TODO: @burkeshartsis to document thoughts and process

**Comment by burke** [comment]
probably the wrong handle

**Comment by conrad-vanl** [comment]
HAH! Thanks

**Comment by burkeshartsis** [comment]
lol 👋

**Comment by redreceipt** [comment]
just a brain dump...

- [] CLI
- [] Launch Screen
- [] Icons
- [] Colors
- [] Onboarding media

**Comment by redreceipt** [comment]
I think we try and get `apollos` back. James Baxley created it on staff at NewSpring. Imagine this:

`apollos init`
`apollos build`
`apollos add-icons [FILES]`

pretty slick...
