### ISSUE TITLE
All ScrollView Components Should ForwardRef 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#673]
### User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

### Description
Forwarding Ref's is useful for Scrolling imperatively.

We probably need to ForwardRef at the highest level possible (before any `styled`) and then pass down the ref with a prop name other than ref, and then at the bottom level (when rendering the ScrollView / FlatList) consume that Ref.  

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
you mention using a different prop name but shouldn't we just use the `forwardRef` HOC so the user doesn't have to know a *different* name, makes the API more straightforward

https://reactjs.org/docs/forwarding-refs.html

**Comment by vinnyjth** [comment]
The user doesn't have to use a different prop name than `ref`, but the component receiving the `ref` has to use a different prop name than `ref`. Check out this branch. 

https://github.com/ApollosProject/apollos-prototype/compare/673-forward-ref

**Comment by redreceipt** [comment]
I have to know to use the `<HorizontalTileFeed forwardedRef={blah}>` prop instead of just being able to use ``<HorizontalTileFeed ref={blah}>`. Don't think that's necessary with the built-in `forwardRef` HOC like this:

<img width="936" alt="Screen Shot 2019-07-22 at 10 52 44 AM" src="https://user-images.githubusercontent.com/2659478/61642461-ea5f3980-ac6e-11e9-8eba-6ed8e3e4f6b8.png">

**Comment by vinnyjth** [comment]
I don't think so.... you use it like <HorizontalTileFeed ref={ref} /> in that in that PR.

**Comment by redreceipt** [comment]
...oh I seen now, you are using it

**Comment by burkeshartsis** [comment]
![](https://media.giphy.com/media/dIxkmtCuuBQuM9Ux1E/giphy.gif)
