### ISSUE TITLE
Export the ContentItem interface fields. 

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#755]
### User Story

As a creator of a new ContentType I should be able to import the base `interface` fields from `server-core`.

### Description
Doing this will make it easier to create new implementations of `ContentItem` and also make sure that clients that upgrade to new versions of the schema with a new implementation get the new fields. 

### Acceptance Criteria

* [ ] Export the base fields used in the `ContentItem` `interface`
* [ ] Also use that new variable to define all of our existing ContentItems. 

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@vinnyjth happy to jump on this one but I may need a little more context.
