### ISSUE TITLE
[Connect] New User Avatar View

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#781]
![image](https://user-images.githubusercontent.com/1637694/59365640-dedf3100-8d06-11e9-8d8f-015f90440edc.png)

### User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by IsaacHardy** [comment]
+1
