### ISSUE TITLE
Disable Notifications

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#809]
### User Story

As a user, I want to be able to disable notifications in the app so the API is aware they are disabled.

### Description

Currently, there's no way to disable notifications without manually doing it in the OS settings but then the app and the API have no idea. We can fix this with an in-app switch.

### Why

I may want to turn off notifications and the API needs to know that information.

### Acceptance Criteria

* [ ] It should have a switch somewhere in the settings that disables notifications.
* [ ] (optional) do the same for location services

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@vinnyjth care if I take a swing at this and just put a simple toggle in the settings menu for now?

**Comment by vinnyjth** [comment]
@redreceipt Totally! Go for it.
