### ISSUE TITLE
Sermon Thumbnails

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#901]
<img width="447" alt="Screen Shot 2019-05-30 at 10 57 22 AM" src="https://user-images.githubusercontent.com/2659478/61663385-82c0e280-ac9e-11e9-8057-3315c3b5f989.png">

### User Story

As a user I want to see an engaging image to click in sermon series content for each sermon.

### Description

Currently sermons are just gray boxes. They should be pretty.

### Why

Because it's ugly.

### Acceptance Criteria

* [ ] It should give sermons images on the tiles inside sermon series content

### Possible Implementation & Open Questions

Maybe they could just default to the parent unless a thumbnail is in Rock.

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by redreceipt** [comment]
@conrad-vanl you care if I take a swing at this? My strategy is:

- Add `ContentItem.thumbnailImage` field
- Pull from a custom attribute in Rock
- Add a prop to `ContentCardConnected` to use thumbnail instead of `coverImage`

**Comment by conrad-vanl** [comment]
sounds good to me! Should this prop also be used for the video thumbnail player?

**Comment by conrad-vanl** [comment]
and i'm not sure that `ContentCardConnected` shuold always use `thumbnailImage`, I think just horizontal content cards should?

**Comment by redreceipt** [comment]
> and i'm not sure that `ContentCardConnected` shuold always use `thumbnailImage`, I think just horizontal content cards should?

I'm sure you're right. I meant the ones at the bottom of a content-single, took a guess :)

**Comment by redreceipt** [comment]
> sounds good to me! Should this prop also be used for the video thumbnail player?

not sure what that is...

**Comment by conrad-vanl** [comment]
The "Play" thumbnail on content singles that you tap on to start the video

**Comment by conrad-vanl** [comment]
> Currently sermons are just gray boxes. They should be pretty.

They are only grey boxes on the newspring app 😉

**Comment by redreceipt** [comment]
> The "Play" thumbnail on content singles that you tap on to start the video

Word. I made an [issue](packages/apollos-ui-scripture/src/index.js) for that too. This solves half of it.

**Comment by redreceipt** [comment]
> > Currently sermons are just gray boxes. They should be pretty.
> 
> They are only grey boxes on the newspring app 😉

Dang. Cold-blooded. I'll look into why we don't match.

**Comment by redreceipt** [comment]
Ok so in thinking about this, I think it would better to have `thumbnail` be a field on `videos` instead of the content item as a whole but that would require changing how we store videos in Apollos Rock to maybe a key/value pair set instead of a single text field. Thoughts?

**Comment by redreceipt** [comment]
cc @vinnyjth ^^^
