### ISSUE TITLE
Skip Onboarding

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#913]
### User Story

Currently, you have to go through onboarding everytime you get signed out of the app.  Would love to just be able to sign in after verifying the phone number if I've already gone through onboarding

### Description

skips onboarding if you already have all the pre-filled information and permissions checks.

### Why

Faster and better UX.

### Acceptance Criteria

* [ ] It should skip right to the home screen after login

### Possible Implementation & Open Questions

query for all the info and permissions checks up front and skip onboarding on login.

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by vinnyjth** [comment]
@redreceipt Can you take a stab at this? We should set a value in local storage that represents if you have done onboarding, and then use that value to direct a user if they login. 

That value should reflect the userId of the user who has done onboarding. So if Jane on Bob's phone signs up, she she do onboarding, even though Bob has already done onboarding.

**Comment by redreceipt** [comment]
then if I get a new phone, I've got to do onboarding again. Shouldn't we just pre-query everything and check permissions and skip if everything is good to go? it'll make the data pop in faster on each screen anyway.

**Comment by vinnyjth** [comment]
New phone means push and location permissions have not been granted. We decided that we wanted new phones to go through onboarding again, for the time being.

**Comment by redreceipt** [comment]
gotcha, cool. probably simpler engineering anyway :)

**Comment by redreceipt** [comment]
I got going on this but the more I think about it, I'm a little unclear. My intention for this issue was to pre-check all the data and permissions and if someone has all that, to skip onboarding. 

I'm not sure what storing a boolean in local storage would do. Currently, if a user is logged in and they've already done onboarding, it already skips ahead. And if someone logs out, it would reset the store anyway so they'd always go back through.

**Comment by vinnyjth** [comment]
> I'm not sure what storing a boolean in local storage would do. Currently, if a user is logged in and they've already done onboarding, it already skips ahead. And if someone logs out, it would reset the store anyway so they'd always go back through.

This might help a bit - I was thinking of storing that flag in `async-storage` local storage, not Apollo's cache :)

**Comment by redreceipt** [comment]
haha yes, that does help. Do you see a problem with just keeping a growing list of `usersCompletedOnboarding`?

**Comment by vinnyjth** [comment]
Nope! I imagine it will rarely be more than 1 user long.
