### ISSUE TITLE
Android - The default map view is zoomed out to the whole world

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#944]
### Details

On android the map view is zoomed out too far, it includes the whole world. When first rendered it should show a region containing all current campuses. 

![image](https://user-images.githubusercontent.com/1637694/62225196-fab99780-b385-11e9-920d-e04ec5b0658c.png)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by vinnyjth** [comment]
Was not able to reproduce in my simulator :/

**Comment by conrad-vanl** [comment]
@vinnyjth I think this happens (on iOS too) based on the speed that data loads. Essentially, the map view has some default view before rthe cmapus are loaded, then what it is supposed to do after loading is zoom in on a view that contains your position and the current campus (this will get triggered when you switch items).

To fix this bug, I think we need to trigger that move/zoom code after all data has loaded and the map has fully initialized, but I'm not sure how to do that.
