### ISSUE TITLE
Devotional Scripture Header Issues

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#950]
### Details

- Tabs at the top are very difficult to tap on iPhone SE
- Tabs can't be tapped on after swiping once on Android
- Scripture link on devotional tab can't be tapped on on Android

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by richarddubay** [comment]
@vinnyjth The "can't be tapped" issue came up again as we were testing. I made an issue in Jira ([DEV-4144](https://newspring.atlassian.net/browse/DEV-4144)). Frank gave this one a high priority as well. Can we add this one to the list of things that you guys are working on?

**Comment by conrad-vanl** [comment]
FWIW, it feels like this issue has to do with a hidden view at the top of the screen that aids in your ability to swipe down from the top. Adding extra vertical spacing above the scripture header could solve this.
