### ISSUE TITLE
[TAB BAR] Scroll to top not working

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#999]
### Details

Quickly navigating back to the top of the Home Feed by tapping on the icon a second time does not appear to be working

### Expected Behavior

Tap on the Home Tab to navigate to the home screen. Scroll down, then tap on the home tab again. The ScrollView should scroll back up to the top.

### Actual Behavior

Tap on the Home Tab to navigate to the home screen. Scroll down, then tap on the home tab again. Nothing happens

### Your Environment

- iPhone XS
- iOS 13

### Steps to Reproduce

_see the expected behavior for an exact breakdown of steps_

**Comment by conrad-vanl** [comment]
This isn't something we can do with react-navigation, unfortunately, and not abug.
